swagger: "2.0"
info:
  description: "Storage Hub brinda servicios para gestionar archivos."
  version: "1.0.0"
  title: "Storage Hub"
basePath: "/api"
schemes:
  - "http"
  - "https"
consumes:
  - "application/json"
produces:
  - "application/json"
tags:
  - name: "file"
    description: "Servicios de gestión de archivos"
securityDefinitions:
  Authorization:
    type: apiKey
    name: Authorization
    in: header
    description: "Bearer JWT token. Formato: 'Authorization: Bearer <token>'"
security:
  - Authorization: []
paths:
  /file:
    get:
      tags:
        - "file"
      summary: "Listar archivos paginados"
      description: "Obtiene TODOS los archivos a los que el usuario tiene permiso."
      operationId: "paginateFiles"
      parameters:
        - name: "pageNumber"
          in: "query"
          description: "Número de página (por defecto 1)"
          required: false
          type: "integer"
          format: "int32"
        - name: "itemsPerPage"
          in: "query"
          description: "Elementos por página (por defecto 5)"
          required: false
          type: "integer"
          format: "int32"
        - name: "search"
          in: "query"
          description: "Búsqueda por nombre de fichero (regex, case‑insensitive)"
          required: false
          type: "string"
        - name: "orderBy"
          in: "query"
          description: "Campo por el que ordenar (ej. createdAt, filename)"
          required: false
          type: "string"
        - name: "orderDesc"
          in: "query"
          description: "true para orden descendente"
          required: false
          type: "boolean"
      responses:
        "200":
          description: "Operación exitosa"
          schema:
            type: "object"
            properties:
              totalItems:
                type: integer
                example: 42
                description: "Total de archivos encontrados"
              page:
                type: integer
                example: 1
                description: "Página actual"
              items:
                type: "array"
                items:
                  $ref: "#/definitions/File"
        "401":
          description: "No autenticado (falta o es inválido el Bearer token)"
        "403":
          description: "No autorizado (sin permisos para listar)"
        "500":
          description: "Error interno al obtener los archivos"
      security:
        - Authorization: []
    post:
      tags:
        - "file"
      summary: "Subir un fichero"
      description: "Permite cargar un fichero."
      operationId: "uploadFile"
      consumes:
        - "multipart/form-data"
      parameters:
        - name: "file"
          in: "formData"
          description: "Archivo a subir"
          required: true
          type: "file"
        - name: "expirationTime"
          in: "formData"
          description: "Tiempo de expiración (días o fecha en string)"
          required: false
          type: "string"
        - name: "isPublic"
          in: "formData"
          description: "true si será público"
          required: false
          type: "boolean"
        - name: "description"
          in: "formData"
          description: "Descripción del fichero"
          required: false
          type: "string"
        - name: "tags"
          in: "formData"
          description: "Etiquetas (separadas por comas)"
          required: false
          type: "string"
      responses:
        "201":
          description: "Fichero subido con éxito"
          schema:
            $ref: "#/definitions/File"
        "400":
          description: "Petición inválida (no se proveyó archivo)"
        "401":
          description: "No autenticado"
        "403":
          description: "Sin permisos para crear"
        "409":
          description: "Error al subir el fichero"
        "413":
          description: "Límite de tamaño excedido o capacidad de almacenamiento"
      security:
        - Authorization: []
  /file/{id}:
    get:
      tags:
        - "file"
      summary: "Obtener fichero por ID"
      description: "Busca un fichero por su identificador."
      operationId: "findFileById"
      parameters:
        - name: "id"
          in: "path"
          description: "ID del fichero (MongoID 24 hex dígitos)"
          required: true
          type: "string"
      responses:
        "200":
          description: "Operación exitosa"
          schema:
            $ref: "#/definitions/File"
        "401":
          description: "No autenticado"
        "403":
          description: "Sin permisos para ver este fichero"
        "404":
          description: "Fichero no encontrado"
        "500":
          description: "Error interno al buscar el fichero"
      security:
        - Authorization: []
    put:
      tags:
        - "file"
      summary: "Reemplazar contenido de un fichero"
      description: "Actualiza el contenido de un fichero existente."
      operationId: "replaceFileContent"
      consumes:
        - "multipart/form-data"
      parameters:
        - name: "id"
          in: "path"
          description: "ID del fichero a reemplazar"
          required: true
          type: "string"
        - name: "file"
          in: "formData"
          description: "Nuevo archivo"
          required: true
          type: "file"
      responses:
        "200":
          description: "Contenido reemplazado correctamente"
        "400":
          description: "Petición inválida (no se proveyó archivo o ID inválido)"
        "401":
          description: "No autenticado"
        "403":
          description: "Sin permisos para actualizar"
        "409":
          description: "Error: extensión no coincide"
        "500":
          description: "Error interno al reemplazar contenido"
      security:
        - Authorization: []
    patch:
      tags:
        - "file"
      summary: "Actualizar metadatos de fichero"
      description: "Cambia descripción, fecha de expiración, etiquetas o visibilidad."
      operationId: "updateFileMetadata"
      consumes:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID del fichero a actualizar"
          required: true
          type: "string"
        - name: "metadata"
          in: "body"
          description: "Campos a actualizar"
          required: true
          schema:
            type: object
            properties:
              description:
                type: string
              expirationDate:
                type: string
              tags:
                type: array
                items:
                  type: string
              isPublic:
                type: boolean
      responses:
        "200":
          description: "Metadatos actualizados"
          schema:
            $ref: "#/definitions/File"
        "400":
          description: "Petición inválida (faltan campos)"
        "401":
          description: "No autenticado"
        "403":
          description: "Sin permisos para actualizar"
        "404":
          description: "Fichero no encontrado"
        "500":
          description: "Error interno al actualizar metadatos"
      security:
        - Authorization: []
    delete:
      tags:
        - "file"
      summary: "Eliminar fichero"
      description: "Borra un fichero, su contenido y actualiza el almacenamiento del usuario."
      operationId: "deleteFile"
      parameters:
        - name: "id"
          in: "path"
          description: "ID del fichero a eliminar"
          required: true
          type: "string"
      responses:
        "200":
          description: "Fichero eliminado correctamente"
          schema:
            type: object
            properties:
              id:
                type: string
              message:
                type: string
                example: "El archivo fue eliminado correctamente."
        "400":
          description: "ID inválido o faltante"
        "401":
          description: "No autenticado"
        "403":
          description: "Sin permisos para eliminar"
        "404":
          description: "Fichero no encontrado"
        "500":
          description: "Error interno al eliminar fichero"
      security:
        - Authorization: []
definitions:
  File:
    type: object
    properties:
      id:
        type: string
      filename:
        type: string
      description:
        type: string
      tags:
        type: array
        items:
          type: string
      mimetype:
        type: string
      encoding:
        type: string
      extension:
        type: string
      type:
        type: string
      relativePath:
        type: string
      absolutePath:
        type: string
      size:
        type: integer
      url:
        type: string
      lastAccess:
        type: string
      createdAt:
        type: string
      createdBy:
        type: object
        properties:
          user:
            type: string
      expirationDate:
        type: string
      isPublic:
        type: boolean
      hits:
        type: integer
      groups:
        type: array
        items:
          type: string
      users:
        type: array
        items:
          type: string
      fileReplaces:
        type: array
        items:
          type: object
          properties:
            user:
              type: string
            date:
              type: string
            username:
              type: string
