"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.FILE_UPDATE_OWN = exports.FILE_UPDATE_ALL = exports.FILE_SHOW_OWN = exports.FILE_SHOW_ALL = exports.FILE_DELETE_OWN = exports.FILE_DELETE_ALL = exports.FILE_CREATE = void 0;
const FILE_SHOW_ALL = "FILE_SHOW_ALL";
exports.FILE_SHOW_ALL = FILE_SHOW_ALL;
const FILE_SHOW_OWN = "FILE_SHOW_OWN";
exports.FILE_SHOW_OWN = FILE_SHOW_OWN;
const FILE_UPDATE_ALL = "FILE_UPDATE_ALL";
exports.FILE_UPDATE_ALL = FILE_UPDATE_ALL;
const FILE_UPDATE_OWN = "FILE_UPDATE_OWN";
exports.FILE_UPDATE_OWN = FILE_UPDATE_OWN;
const FILE_CREATE = "FILE_CREATE";
exports.FILE_CREATE = FILE_CREATE;
const FILE_DELETE_ALL = "FILE_DELETE_ALL";
exports.FILE_DELETE_ALL = FILE_DELETE_ALL;
const FILE_DELETE_OWN = "FILE_DELETE_OWN";
exports.FILE_DELETE_OWN = FILE_DELETE_OWN;