"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.USER_STORAGE_DELETE = exports.USER_STORAGE_CREATE = exports.USER_STORAGE_UPDATE = exports.USER_STORAGE_SHOW = void 0;
const USER_STORAGE_SHOW = "USER_STORAGE_SHOW";
exports.USER_STORAGE_SHOW = USER_STORAGE_SHOW;
const USER_STORAGE_UPDATE = "USER_STORAGE_UPDATE";
exports.USER_STORAGE_UPDATE = USER_STORAGE_UPDATE;
const USER_STORAGE_CREATE = "USER_STORAGE_CREATE";
exports.USER_STORAGE_CREATE = USER_STORAGE_CREATE;
const USER_STORAGE_DELETE = "USER_STORAGE_DELETE";
exports.USER_STORAGE_DELETE = USER_STORAGE_DELETE;