"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.USER_STORAGE_UPDATE = exports.USER_STORAGE_SHOW_OWN = exports.USER_STORAGE_SHOW_ALL = exports.USER_STORAGE_DELETE = exports.USER_STORAGE_CREATE = void 0;
const USER_STORAGE_SHOW_ALL = "USER_STORAGE_SHOW_ALL";
exports.USER_STORAGE_SHOW_ALL = USER_STORAGE_SHOW_ALL;
const USER_STORAGE_SHOW_OWN = "USER_STORAGE_SHOW_OWN";
exports.USER_STORAGE_SHOW_OWN = USER_STORAGE_SHOW_OWN;
const USER_STORAGE_UPDATE = "USER_STORAGE_UPDATE";
exports.USER_STORAGE_UPDATE = USER_STORAGE_UPDATE;
const USER_STORAGE_CREATE = "USER_STORAGE_CREATE";
exports.USER_STORAGE_CREATE = USER_STORAGE_CREATE;
const USER_STORAGE_DELETE = "USER_STORAGE_DELETE";
exports.USER_STORAGE_DELETE = USER_STORAGE_DELETE;