"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.USERSTORAGE_DELETE = exports.USERSTORAGE_CREATE = exports.USERSTORAGE_UPDATE = exports.USERSTORAGE_SHOW = void 0;
const USERSTORAGE_SHOW = "USERSTORAGE_SHOW";
exports.USERSTORAGE_SHOW = USERSTORAGE_SHOW;
const USERSTORAGE_UPDATE = "USERSTORAGE_UPDATE";
exports.USERSTORAGE_UPDATE = USERSTORAGE_UPDATE;
const USERSTORAGE_CREATE = "USERSTORAGE_CREATE";
exports.USERSTORAGE_CREATE = USERSTORAGE_CREATE;
const USERSTORAGE_DELETE = "USERSTORAGE_DELETE";
exports.USERSTORAGE_DELETE = USERSTORAGE_DELETE;