"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.NOTIFICATION_UPDATE = exports.NOTIFICATION_SHOW = exports.NOTIFICATION_CREATE = void 0;
var NOTIFICATION_SHOW = exports.NOTIFICATION_SHOW = "NOTIFICATION_SHOW";
var NOTIFICATION_UPDATE = exports.NOTIFICATION_UPDATE = "NOTIFICATION_UPDATE";
var NOTIFICATION_CREATE = exports.NOTIFICATION_CREATE = "NOTIFICATION_CREATE";