const DOMAIN_SHOW = "DOMAIN_SHOW"
const DOMAIN_CREATE = "DOMAIN_CREATE"
const DOMAIN_UPDATE = "DOMAIN_UPDATE"
const DOMAIN_DELETE = "DOMAIN_DELETE"

module.exports = {
    DOMAIN_SHOW, DOMAIN_CREATE, DOMAIN_UPDATE, DOMAIN_DELETE
}