export const DOMAIN_SHOW = "DOMAIN_SHOW"
export const DOMAIN_CREATE = "DOMAIN_CREATE"
export const DOMAIN_UPDATE = "DOMAIN_UPDATE"
export const DOMAIN_DELETE = "DOMAIN_DELETE"

export default {
    DOMAIN_SHOW,
    DOMAIN_CREATE,
    DOMAIN_UPDATE,
    DOMAIN_DELETE,
}