
const AUDIT_MENU = "AUDIT_MENU"
const AUDIT_SHOW = "AUDIT_SHOW"
const AUDIT_UPDATE = "AUDIT_UPDATE"
const AUDIT_CREATE = "AUDIT_CREATE"
const AUDIT_DELETE = "AUDIT_DELETE"

module.exports = {
    AUDIT_MENU,
    AUDIT_CREATE,
    AUDIT_SHOW,
    AUDIT_UPDATE,
    AUDIT_DELETE
}
    