export const USER_STORAGE_SHOW_ALL = "USER_STORAGE_SHOW_ALL";
export const USER_STORAGE_SHOW_OWN = "USER_STORAGE_SHOW_OWN";
export const USER_STORAGE_UPDATE = "USER_STORAGE_UPDATE";
export const USER_STORAGE_CREATE = "USER_STORAGE_CREATE";
export const USER_STORAGE_DELETE = "USER_STORAGE_DELETE";
