
swagger: "2.0"
info:
  description: "Dracul Media Storage es una aplicación que brinda servicios para almacenar archivos."
  version: "1.0.0"
  title: "Dracul Media Storage"
basePath: "/"
tags:
- name: "file"
  description: "Servicios para interactuar con archivos"
schemes:
- "http"
- "https"
paths:
  /file:
    get:
      tags:
      - "file"
      summary: "Busca archivos paginado"
      operationId: "findFile"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "pageNumber"
        in: "path"
        description: "Número de página"
        required: false
      - name: "itemsPerPage"
        in: "path"
        description: "Cantidad de items por página"
        required: false
      - name: "search"
        in: "path"
        description: "Elemento buscado"
        required: false
      - name: "orderBy"
        in: "path"
        description: "Tipo de orden"
        required: false
      - name: "orderDesc"
        in: "path"
        description: "Booleano para que la query devuelve resultado ordenado en forma descendente"
        required: false
      responses:
        '200':
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/File"
        '400':
          description: "Invalid status value"
      security:
      - Authorization: []
    post:
      tags:
      - "file"
      summary: "Guarda un archivo"
      operationId: "postFile"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "file"
        in: "formData"
        description: "Archivo a subir"
        required: true
        type: "file"
      responses:
        '200':
          description: "successful operation"
          schema:
            type: "object"
            $ref: "#/definitions/File"
        '400':
          description: "Invalid status value"
      security:
      - Authorization: []
  /file/{id}:
    get:
      tags:
      - "file"
      summary: "Busca archivos por id"
      operationId: "findFileById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "Id del archivo"
        required: true
        type: "string"
      responses:
        '200':
          description: "successful operation"
          schema:
            type: "object"
            $ref: "#/definitions/File"
        '400':
          description: "Invalid status value"
      security:
      - Authorization: []
securityDefinitions:
  Authorization:
    type: "apiKey"
    scheme: "bearer"
    name: "Authorization"
    in: "header"
    bearerFormat: JWT
definitions:
  File:
    type: "object"
    required:
    - "_id"
    - "extesion"
    - "relativePath"
    - "absolutePath"
    - "size"
    - "url"
    - "createdAt"
    - "deleted"
    - "deletedAt"
    - "filename"
    - "mimetype"
    - "buffer"
    - "encoding"
    properties:
      _id:
        type: String
        example: "6155cf0e8a582e2fb347731e"
      extension:
        type: String
        example: ".png"
      relativePath:
        type: String
        example: "media/files/root/2021/9/foto.png"
      absolutePath:
        type: String
        example: "/home/user/Projects/modular-framework/packages/media/media-backend/media/files/root/2021/9/foto.png"
      size:
        type: integer
        example: 20097
      url:
        type: String
        example: "http://localhost:7000/media/files/root/2021/9/foto.png"
      createdAt:
        type: String
        example: "2021-09-30T14:51:58.968Z"
      deleted:
        type: boolean
        example: false
      deletedAt:
        type: String
        example: "2021-09-30T14:51:58.968Z"
      extension:
        type: String
        example: ".png"
      filename:
        type: "string"
        example: "foto.jpg"
      mimetype:
        type: "string"
        example: "image/png"
      buffer:
        type: "string"
      encoding:
        type: "string"
        example: "7bit"